### ISSUE TITLE
Airdrop for zgbjmy2008

### ISSUE THREAD

**Issue by zgbjmy2009** [web3actions/web3actions.github.io#90]
{"address":"0x001fd2ab86b5cf5a3892f60048c5cc30dfab081c"}
hi there,this cool!

**Comment by mktcode** [comment]
Hey @zgbjmy2009 ! Glad you tried this.

> Airdrop already claimed or oracle fee not payed for @zgbjmy2009.

That's actually not true. The message is a bit misleading. You can simply try again by opening another issue. But the content must be only `{"address":"0x001fd2ab86b5cf5a3892f60048c5cc30dfab081c"}` without any additional comments.
